### ISSUE TITLE
Include get val

### ISSUE THREAD

**Issue by gbgelado** [derrickpelletier/node-status#14]
please include:

`Item.prototype = {`
`  inc: function(amount){`
`    this.val += (amount !== undefined) ? amount : 1;`
`  },`
` `
`  dec: function(amount){`
`    this.val -= (amount !== undefined) ? amount : 1;`
`  },`
` `
`  val: function(){`
`    return this.val;`
`  },`
`}`

**Comment by derrickpelletier** [comment]
so you can call `item.val()`? I don't think this will work really, you're asking to have a property and a function of the same name on the same object?

What purpose is this for?

**Comment by gbgelado** [comment]
Get the current value if you need it

**Comment by derrickpelletier** [comment]
You can't just use `item.val` in this situation?
