### ISSUE TITLE
Clear and start another?

### ISSUE THREAD

**Issue by slavafomin** [derrickpelletier/node-status#16]
Hello!

Could you please give an example of how one progress bar could be stopped and another one started?

Right now, I'm calling:

```js
status.clear();
status.removeAll();
```

between two progress bar executions, but it didn't reset the time counter for some reason.

**Comment by derrickpelletier** [comment]
`clear()` is purely visual, it just erases the current line from the tty.

I guess you could just set the `count` and `max` on each of your items to 0?
There is no implemented support to completely wipe out a status bar.

**Comment by derrickpelletier** [comment]
Closing this, should be accommodated in #18 more or less
